### PR TITLE
Adding a section on Azure Arc

### PR DESCRIPTION
**Pull request by rcheeran**
Removing the Azure Device Agent section and Adding a section on Azure Arc for Servers

### CODE REVIEW

**Comment by rcheeran** [comment]
@parameshbabu for review

**Comment by parameshbabu** [comment]
LGTM.

**Review by parameshbabu — APPROVED** [review]

**Review by TerryWarwick — CHANGES_REQUESTED** [review]
Please update this link to remove the en-us reference.  I believe you can also shorten it like the others

**Comment by rcheeran** [comment]
Updated the link to remove the en-us references.

**Pull request merged**
